export const SET_QUERY = 'SET_QUERY';
export const RESET_QUERY = 'RESET_QUERY';

export const FETCH_SEARCH_RESULTS = 'FETCH_SEARCH_RESULTS';
export const IS_FETCHING_SEARCH_RESULTS = 'IS_FETCHING_SEARCH_RESULTS';