export const FETCH_MOVIE_DETAILS = 'FETCH_MOVIE_DETAILS';
export const IS_FETCHING = 'IS_FETCHING';
export const IS_FETCHING_DETAILS = 'IS_FETCHING_DETAILS';
export const FETCH_ALL_SIMILAR = 'FETCH_ALL_SIMILAR';
export const FETCH_ALL_RECOMMENDATIONS = 'FETCH_ALL_RECOMMENDATIONS';
export const FETCH_DETAILS_SUCCESS = 'FETCH_DETAILS_SUCCESS';
export const IS_FETCHING_NOWPLAYING = 'IS_FETCHING_NOWPLAYING';
export const SET_RATING = "SET_RATING";


