export const FETCH_FAVORITES = 'FETCH_FAVORITES';
export const FETCH_WATCHLIST = 'FETCH_WATCHLIST';
export const CHECK_IF_FAVORITE_WATCHLIST = 'CHECK_IF_FAVORITE_WATCHLIST';
export const IS_FETCHING = 'IS_FETCHING';
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const ADD_TO_WATCHLIST = 'ADD_TO_WATCHLIST';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
export const REMOVE_WATCHLIST = 'REMOVE_WATCHLIST';



