export const GET_USER_LISTS = 'GET_USER_LISTS';
export const GET_LIST = 'GET_LIST';
export const ADD_INFO_TO_LIST = 'ADD_INFO_TO_LIST';

export const CREATE_USER_LIST = 'CREATE_USER_LIST';
export const CHECK_ITEM_STATUS = 'CHECK_ITEM_STATUS';
export const ADD_MOVIE_TO_LIST= 'ADD_MOVIE_TO_LIST';
export const REMOVE_FROM_LIST ='REMOVE_FROM_LIST';
export const CLEAR_LIST = 'CLEAR_LIST';
export const DELETE_LIST = 'DELETE_LIST';
export const IS_FETCHING_LISTS= 'IS_FETCHING_LISTS';
export const IS_FETCHING_CURRENT_LIST= 'IS_FETCHING_CURRENT_LIST';

export const USER_INPUT_NAME='USER_INPUT_NAME';
export const USER_INPUT_DESCRIPTION='USER_INPUT_DESCRIPTION'; 
export const SEARCH_QUERY = 'SEARCH_QUERY';
export const GET_SUGGESTIONS = 'GET_SUGGESTIONS';
export const IS_FETCHING_SUGGESTIONS = 'IS_FETCHING_SUGGESTIONS';
export const FETCH_FAILED = 'FETCH_FAILED';

export const FETCH_LIST_ITEMS = 'FETCH_LIST_ITEMS';

export const TOGGLE_DROPDOWN = 'TOGGLE_DROPDOWN';


